apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordhex-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordhex
  template:
    metadata:
      labels:
        app: wordhex
    spec:
      containers:
      - name: wordhex-container
        image: wordhex:react
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wordhex-svc
spec:
  selector:
    app: wordhex
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordhex-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "wordhex.local"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordhex-svc
            port:
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordhex-ingress-https
  annotations:
    cert-manager.io/issuer: default-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: "wordhex.zachandrews.com"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordhex-svc
            port:
              number: 3000
  tls:
  - hosts:
    - "wordhex.zachandrews.com"
    secretName: wordhex-cert
